services:
  - type: web
    name: telegram-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python TelegramBotu.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7806413438:AAGao-5vJdpxxydutLHE_tl6rSIFm9MUeb4
    autoDeploy: true 